name: Build wheels for pjsua2 on Linux x86_64

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  job_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build linux x86_64 wheels
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux_2_28_x86_64
        with:
          python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311'
          build-requirements: 'pydub requests PyYAML typing_extensions'
          system-packages: 'epel-release swig python3-devel python3-pip python3-wheel'
          package-path: 'pjsip-apps/src/swig/python'
          pre-build-command: 'sh build-pjsua2.sh'

      - name: add artifacts to gh-release
        uses: ncipollo/release-action@main
        with:
          artifacts: "pjsip-apps/src/swig/python/dist/*manylinux*"
          name: PJSIP version ${{ github.ref_name }}
          removeArtifacts: true
          replacesArtifacts: true
          allowUpdates: true
          omitNameDuringUpdate: true
          artifactErrorsFailBuild: false
          omitBody: true
          generateReleaseNotes: true
