name: Build wheels for pjsua2 on Linux x86_64

on:
  release:
    types: [created]
    paths-ignore:
      - '.github/workflows/build-wheels-linux-aarch64.yml'
  push:
    branches: [ wheels ]
    paths-ignore:
      - '.github/workflows/build-wheels-linux-aarch64.yml'
      
jobs:
  job_linux_x86_64:
    runs-on: ubuntu-latest
    name: Build Linux x86_64 wheels
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: wheels

      - name: Linux x86_64 wheels
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
        with:
          python-versions: 'cp310-cp310'
          build-requirements: 'pydub requests PyYAML typing_extensions'
          system-packages: 'epel-release swig python3-devel python3-pip python3-wheel python-pip python-wheel'
          package-path: 'pjsip-apps/src/swig/python'
          pre-build-command: 'sh build-pjsua2.sh'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
        
          path: pjsip-apps/src/swig/python/dist/*manylinux*

#    - name: Publish wheels to PyPI
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        twine upload dist/*-manylinux*.whl
